insert into paises (nombre, nacionalidad, iso_2, iso_3) values
('Afganistán', 'afgana', 'AF', 'AFG'),
('Albania', 'albanesa', 'AL', 'ALB'),
('Alemania', 'alemana', 'DE', 'DEU'),
('Andorra', 'andorrana', 'AD', 'AND'),
('Angola', 'angoleña', 'AO', 'AGO'),
('Antigua y Barbuda', 'antiguana', 'AG', 'ATG'),
('Arabia Saudita', 'saudí', 'SA', 'SAU'),
('Argelia', 'argelina', 'DZ', 'DZA'),
('Argentina', 'argentina', 'AR', 'ARG'),
('Armenia', 'armenia', 'AM', 'ARM'),
('Australia', 'australiana', 'AU', 'AUS'),
('Austria', 'austriaca', 'AT', 'AUT'),
('Azerbaiyán', 'azerbaiyana', 'AZ', 'AZE'),
('Bahamas', 'bahamense', 'BS', 'BHS'),
('Bangladés', 'bangladesí', 'BD', 'BGD'),
('Barbados', 'barbadense', 'BB', 'BRB'),
('Baréin', 'bareiní', 'BH', 'BHR'),
('Bélgica', 'belga', 'BE', 'BEL'),
('Belice', 'beliceña', 'BZ', 'BLZ'),
('Benín', 'beninesa', 'BJ', 'BEN'),
('Bielorrusia', 'bielorrusa', 'BY', 'BLR'),
('Birmania', 'birmana', 'MM', 'MMR'),
('Bolivia', 'boliviana', 'BO', 'BOL'),
('Bosnia y Herzegovina', 'bosnia', 'BA', 'BIH'),
('Botsuana', 'botsuana', 'BW', 'BWA'),
('Brasil', 'brasileña', 'BR', 'BRA'),
('Brunéi', 'bruneana', 'BN', 'BRN'),
('Bulgaria', 'búlgara', 'BG', 'BGR'),
('Burkina Faso', 'burkinés', 'BF', 'BFA'),
('Burundi', 'burundesa', 'BI', 'BDI'),
('Bután', 'butanesa', 'BT', 'BTN'),
('Cabo Verde', 'caboverdiana', 'CV', 'CPV'),
('Camboya', 'camboyana', 'KH', 'KHM'),
('Camerún', 'camerunesa', 'CM', 'CMR'),
('Canadá', 'canadiense', 'CA', 'CAN'),
('Catar', 'catarí', 'QA', 'QAT'),
('Chad', 'chadiana', 'TD', 'TCD'),
('Chile', 'chilena', 'CL', 'CHL'),
('China', 'china', 'CN', 'CHN'),
('Chipre', 'chipriota', 'CY', 'CYP'),
('Colombia', 'colombiana', 'CO', 'COL'),
('Comoras', 'comorense', 'KM', 'COM'),
('Corea del Norte', 'norcoreana', 'KP', 'PRK'),
('Corea del Sur', 'surcoreana', 'KR', 'KOR'),
('Costa de Marfil', 'marfileña', 'CI', 'CIV'),
('Costa Rica', 'costarricense', 'CR', 'CRI'),
('Croacia', 'croata', 'HR', 'HRV'),
('Cuba', 'cubana', 'CU', 'CUB'),
('Dinamarca', 'danesa', 'DK', 'DNK'),
('Dominica', 'dominiquesa', 'DM', 'DMA'),
('Ecuador', 'ecuatoriana', 'EC', 'ECU'),
('Egipto', 'egipcia', 'EG', 'EGY'),
('El Salvador', 'salvadoreña', 'SV', 'SLV'),
('Emiratos Árabes Unidos', 'emiratí', 'AE', 'ARE'),
('Eritrea', 'eritrea', 'ER', 'ERI'),
('Eslovaquia', 'eslovaca', 'SK', 'SVK'),
('Eslovenia', 'eslovena', 'SI', 'SVN'),
('España', 'española', 'ES', 'ESP'),
('Estados Unidos', 'estadounidense', 'US', 'USA'),
('Estonia', 'estonia', 'EE', 'EST'),
('Etiopía', 'etíope', 'ET', 'ETH'),
('Filipinas', 'filipina', 'PH', 'PHL'),
('Finlandia', 'finlandesa', 'FI', 'FIN'),
('Fiyi', 'fiyiana', 'FJ', 'FJI'),
('Francia', 'francesa', 'FR', 'FRA'),
('Gabón', 'gabonesa', 'GA', 'GAB'),
('Gambia', 'gambiana', 'GM', 'GMB'),
('Georgia', 'georgiana', 'GE', 'GEO'),
('Ghana', 'ghanesa', 'GH', 'GHA'),
('Granada', 'granadina', 'GD', 'GRD'),
('Grecia', 'griega', 'GR', 'GRC'),
('Guatemala', 'guatemalteca', 'GT', 'GTM'),
('Guinea', 'guineana', 'GN', 'GIN'),
('Guinea Ecuatorial', 'ecuatoguineana', 'GQ', 'GNQ'),
('Guinea-Bisáu', 'guineana', 'GW', 'GNB'),
('Guyana', 'guyanesa', 'GY', 'GUY'),
('Haití', 'haitiana', 'HT', 'HTI'),
('Honduras', 'hondureña', 'HN', 'HND'),
('Hungría', 'húngara', 'HU', 'HUN'),
('India', 'india', 'IN', 'IND'),
('Indonesia', 'indonesia', 'ID', 'IDN'),
('Irak', 'iraquí', 'IQ', 'IRQ'),
('Irán', 'iraní', 'IR', 'IRN'),
('Irlanda', 'irlandesa', 'IE', 'IRL'),
('Islandia', 'islandesa', 'IS', 'ISL'),
('Islas Marshall', 'marshaliana', 'MH', 'MHL'),
('Islas Salomón', 'salomonense', 'SB', 'SLB'),
('Israel', 'israelí', 'IL', 'ISR'),
('Italia', 'italiana', 'IT', 'ITA'),
('Jamaica', 'jamaicana', 'JM', 'JAM'),
('Japón', 'japonesa', 'JP', 'JPN'),
('Jordania', 'jordana', 'JO', 'JOR'),
('Kazajistán', 'kazaja', 'KZ', 'KAZ'),
('Kenia', 'keniana', 'KE', 'KEN'),
('Kirguistán', 'kirguisa', 'KG', 'KGZ'),
('Kiribati', 'kiribatiana', 'KI', 'KIR'),
('Kuwait', 'kuwaití', 'KW', 'KWT'),
('Laos', 'laosiana', 'LA', 'LAO'),
('Lesoto', 'lesotense', 'LS', 'LSO'),
('Letonia', 'letona', 'LV', 'LVA'),
('Líbano', 'libanesa', 'LB', 'LBN'),
('Liberia', 'liberiana', 'LR', 'LBR'),
('Libia', 'libia', 'LY', 'LBY'),
('Liechtenstein', 'liechtensteiniana', 'LI', 'LIE'),
('Lituania', 'lituana', 'LT', 'LTU'),
('Luxemburgo', 'luxemburguesa', 'LU', 'LUX'),
('Madagascar', 'malgache', 'MG', 'MDG'),
('Malasia', 'malaya', 'MY', 'MYS'),
('Malaui', 'malauí', 'MW', 'MWI'),
('Maldivas', 'maldiva', 'MV', 'MDV'),
('Malí', 'maliense', 'ML', 'MLI'),
('Malta', 'maltesa', 'MT', 'MLT'),
('Marruecos', 'marroquí', 'MA', 'MAR'),
('Mauricio', 'mauriciana', 'MU', 'MUS'),
('Mauritania', 'mauritana', 'MR', 'MRT'),
('México', 'mexicana', 'MX', 'MEX'),
('Micronesia', 'micronesia', 'FM', 'FSM'),
('Moldavia', 'moldava', 'MD', 'MDA'),
('Mónaco', 'monegasca', 'MC', 'MCO'),
('Mongolia', 'mongola', 'MN', 'MNG'),
('Montenegro', 'montenegrina', 'ME', 'MNE'),
('Mozambique', 'mozambiqueña', 'MZ', 'MOZ'),
('Namibia', 'namibia', 'NA', 'NAM'),
('Nauru', 'nauruana', 'NR', 'NRU'),
('Nepal', 'nepalesa', 'NP', 'NPL'),
('Nicaragua', 'nicaragüense', 'NI', 'NIC'),
('Níger', 'nigerina', 'NE', 'NER'),
('Nigeria', 'nigeriana', 'NG', 'NGA'),
('Noruega', 'noruega', 'NO', 'NOR'),
('Nueva Zelanda', 'neozelandesa', 'NZ', 'NZL'),
('Omán', 'omaní', 'OM', 'OMN'),
('Países Bajos', 'neerlandesa', 'NL', 'NLD'),
('Pakistán', 'pakistaní', 'PK', 'PAK'),
('Palaos', 'palauana', 'PW', 'PLW'),
('Panamá', 'panameña', 'PA', 'PAN'),
('Papúa Nueva Guinea', 'papú', 'PG', 'PNG'),
('Paraguay', 'paraguaya', 'PY', 'PRY'),
('Perú', 'peruana', 'PE', 'PER'),
('Polonia', 'polaca', 'PL', 'POL'),
('Portugal', 'portuguesa', 'PT', 'PRT'),
('Reino Unido', 'británica', 'GB', 'GBR'),
('República Centroafricana', 'centroafricana', 'CF', 'CAF'),
('República Checa', 'checa', 'CZ', 'CZE'),
('República Democrática del Congó', 'congoleña', 'CD', 'COD'),
('República Dominicana', 'dominicana', 'DO', 'DOM'),
('Ruanda', 'ruandesa', 'RW', 'RWA'),
('Rumanía', 'rumana', 'RO', 'ROU'),
('Rusia', 'rusa', 'RU', 'RUS'),
('Samoa', 'samoana', 'WS', 'WSM'),
('San Cristóbal y Nieves', 'sancristobaleña', 'KN', 'KNA'),
('San Marino', 'sanmarinense', 'SM', 'SMR'),
('San Vicente y las Granadinas', 'sanvicentina', 'VC', 'VCT'),
('Santa Lucía', 'santalucense', 'LC', 'LCA'),
('Santo Tomé y Príncipe', 'santotomeña', 'ST', 'STP'),
('Senegal', 'senegalesa', 'SN', 'SEN'),
('Serbia', 'serbia', 'RS', 'SRB'),
('Seychelles', 'seychellense', 'SC', 'SYC'),
('Sierra Leona', 'sierraleonesa', 'SL', 'SLE'),
('Singapur', 'singapurense', 'SG', 'SGP'),
('Siria', 'siria', 'SY', 'SYR'),
('Somalia', 'somalí', 'SO', 'SOM'),
('Sri Lanka', 'ceilandesa', 'LK', 'LKA'),
('Suazilandia', 'suazi', 'SZ', 'SWZ'),
('Sudáfrica', 'sudafricana', 'ZA', 'ZAF'),
('Sudán', 'sudanesa', 'SD', 'SDN'),
('Sudán del Sur', 'sudansureña', 'SS', 'SSD'),
('Suecia', 'sueca', 'SE', 'SWE'),
('Suiza', 'suiza', 'CH', 'CHE'),
('Surinam', 'surinamesa', 'SR', 'SUR'),
('Tailandia', 'tailandesa', 'TH', 'THA'),
('Tanzania', 'tanzana', 'TZ', 'TZA'),
('Tayikistán', 'tayika', 'TJ', 'TJK'),
('Timor Oriental', 'timorense', 'TL', 'TLS'),
('Togo', 'to golesa', 'TG', 'TGO'),
('Tonga', 'tongana', 'TO', 'TON'),
('Trinidad y Tobago', 'trinitense', 'TT', 'TTO'),
('Túnez', 'tunecina', 'TN', 'TUN'),
('Turkmenistán', 'turcomana', 'TM', 'TKM'),
('Turquía', 'turca', 'TR', 'TUR'),
('Tuvalu', 'tuvaluana', 'TV', 'TUV'),
('Ucrania', 'ucraniana', 'UA', 'UKR'),
('Uganda', 'ugandesa', 'UG', 'UGA'),
('Uruguay', 'uruguaya', 'UY', 'URY'),
('Uzbekistán', 'uzbeka', 'UZ', 'UZB'),
('Vanuatu', 'vanuatuense', 'VU', 'VUT'),
('Vaticano', 'vaticana', 'VA', 'VAT'),
('Venezuela', 'venezolana', 'VE', 'VEN'),
('Vietnam', 'vietnamita', 'VN', 'VNM'),
('Yemen', 'yemení', 'YE', 'YEM'),
('Yibuti', 'yibutiana', 'DJ', 'DJI'),
('Zambia', 'zambiana', 'ZM', 'ZMB'),
('Zimbabue', 'zimbabuense', 'ZW', 'ZWE');